### ISSUE TITLE
Minor fixes in ortography 

### ISSUE THREAD

**Issue by Lenugo** [Edwardb11/edwardb11.github.io#10]
¡Tienes un buen portafolio!. Agrégale mas valor corrigiendo las faltas ortográficas. 
> - 1: Agrega un espacio antes de la coma (,)  en *Bootstrap*,
> - 2: Quítale la coma (,) después de *Git*.
![Captura de pantalla (81)_LI](https://user-images.githubusercontent.com/54646168/165408163-24690a56-fbab-4a47-b9d9-99aac055f95b.jpg)
**LGTM!**

**Comment by Edwardb11** [comment]
Gracias por las observaciones 💯 @Lenugo
